"""LLM overlay — Phase 5.

Non-load-bearing: any failure returns the original signal unchanged.
LLM may veto (side→"hold", strength=0.0) or adjust strength ∈ [0.0, 1.0].
It never originates a trade, flips buy↔sell, or sets position size.
"""
from __future__ import annotations

import json
import logging
import re
import time

import pandas as pd

from trader.overlay.cost_tracking import estimate_cost_usd
from trader.overlay.llm_client import call_llm
from trader.overlay.market_stats import compute_bar_stats
from trader.overlay.news_context import fetch_news
from trader.strategy.base import Signal

logger = logging.getLogger(__name__)

# ---- In-process overlay cache ----

# (symbol, side) -> (monotonic_timestamp, Signal)
_OVERLAY_CACHE: dict[tuple[str, str], tuple[float, Signal]] = {}
_OVERLAY_TTL = 1800.0  # 30 minutes


def _clear_overlay_cache() -> None:
    """Test helper — clears the in-process overlay cache."""
    _OVERLAY_CACHE.clear()


def _log_llm_call(repo, provider: str, symbol: str, cache_hit: bool, usage) -> None:
    """Best-effort cost-log write. Never raises — logging must not affect the overlay."""
    if repo is None:
        return
    try:
        repo.record_llm_call(
            provider=provider,
            call_site="overlay",
            symbol=symbol,
            cache_hit=cache_hit,
            input_tokens=usage.input_tokens if usage else 0,
            output_tokens=usage.output_tokens if usage else 0,
            est_cost_usd=estimate_cost_usd(usage),
        )
    except Exception:
        logger.warning("llm call-log write failed for %s", symbol, exc_info=True)


# ---- System prompts ----

_EQUITY_SYSTEM_PROMPT = """\
You are a senior quantitative equity analyst at a systematic trading fund. You review
trade signals generated by moving-average crossover strategies on US equities.
Trades are swing positions (2-5 day holds). A hard risk gate enforces position limits
regardless of your output.

VETO the signal if ANY of the following apply:
- Earnings release scheduled within the next 2 trading days for this stock
- Major FDA, DOJ, SEC, or regulatory decision expected imminently
- Stock gapped more than 3% at today's open (momentum signal is stale/unreliable)
- Clearly adverse breaking news: executive departure, fraud allegation, major litigation,
  product recall, credit downgrade, or similar material negative event
- Broad market circuit-breaker conditions or Federal Reserve rate decision same day

REDUCE STRENGTH (approve with lower value) for:
- Elevated but non-decisive uncertainty (sector rotation, mild macro headwinds)
- Mixed news with no clear material catalyst

APPROVE with original strength when:
- News is neutral, positive, or irrelevant to the signal thesis
- No news available or you are uncertain — default bias is APPROVE, not veto

Before deciding, briefly weigh the strongest bull case (why this signal is valid now)
against the strongest bear case (why this signal might be wrong) given the news context.
Let that tension inform your strength value and whether to veto.

Reserve veto for clear, material, signal-invalidating events only. A false veto costs
edge; a missed veto costs at most one trade — the risk gate still protects.

If recent trade history for this symbol is provided below, weigh it — for an entry
signal, a recent stop-out from the same strategy is a caution signal but not an
automatic veto; for an exit signal, a recent loss is not a reason to veto the exit
itself (a vetoed sell just strands the position). Use judgment either way.

NEVER flip buy to sell or sell to buy. NEVER originate a trade. NEVER increase
strength above what the strategy reported.

Respond ONLY with valid JSON — no markdown, no text outside the JSON object:
{"action": "approve"|"veto", "strength": <float 0.0-1.0>, "rationale": "<one sentence>"}
"""

_CRYPTO_SYSTEM_PROMPT = """\
You are a senior quantitative crypto analyst at a systematic trading fund. You review
trade signals generated by EMA crossover strategies on crypto assets (BTC/USD, ETH/USD,
and similar). The market runs 24/7 with no earnings events. A hard risk gate enforces
position limits regardless of your output.

VETO the signal if ANY of the following apply:
- Major exchange hack, insolvency, or trading halt announced (Binance, Coinbase, Kraken, etc.)
- Network-level exploit or critical smart contract vulnerability disclosed for this asset
- Concrete government ban or seizure order targeting this specific cryptocurrency
- Clearly adverse breaking news: founder fraud, protocol failure, major de-pegging event
- Broad market circuit-breaker conditions or Federal Reserve rate decision same day

REDUCE STRENGTH (approve with lower value) for:
- Elevated regulatory uncertainty without a concrete ban (proposed legislation, warnings)
- Mixed sentiment with no clear material catalyst
- Unusually high volatility without a directional catalyst

APPROVE with original strength when:
- News is neutral, positive, or irrelevant to the signal thesis
- No news available or you are uncertain — default bias is APPROVE, not veto

Before deciding, briefly weigh the strongest bull case (why this signal is valid now)
against the strongest bear case (why this signal might be wrong) given the news context.
Let that tension inform your strength value and whether to veto.

Reserve veto for clear, material, signal-invalidating events only. A false veto costs
edge; a missed veto costs at most one trade — the risk gate still protects.

If recent trade history for this symbol is provided below, weigh it — for an entry
signal, a recent stop-out from the same strategy is a caution signal but not an
automatic veto; for an exit signal, a recent loss is not a reason to veto the exit
itself (a vetoed sell just strands the position). Use judgment either way.

NEVER flip buy to sell or sell to buy. NEVER originate a trade. NEVER increase
strength above what the strategy reported.

Respond ONLY with valid JSON — no markdown, no text outside the JSON object:
{"action": "approve"|"veto", "strength": <float 0.0-1.0>, "rationale": "<one sentence>"}
"""


def _bars_context(symbol: str, bars: pd.DataFrame) -> str:
    stats = compute_bar_stats(bars)
    if not stats:
        return f"Insufficient bar data for {symbol}."
    return (
        f"Market context ({symbol}, last {stats['n_days']} trading days):\n"
        f"- Last close: ${stats['last_close']:.2f}\n"
        f"- {stats['lookback_20']}-day price change: {stats['pct_20d']:+.1f}%\n"
        f"- {stats['lookback_10']}-day annualized volatility: {stats['vol_10d_annualized']:.1f}%"
    )


def _parse_response(text: str) -> dict:
    """Parse LLM response, stripping markdown fences if present."""
    text = text.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    return json.loads(text.strip())


def apply_claude_overlay(
    signal: Signal,
    bars: pd.DataFrame,
    groq_key: str | None,
    groq_model: str,
    claude_key: str | None,
    claude_model: str,
    gemini_key: str | None = None,
    gemini_model: str = "gemini-3.1-flash-lite",
    config=None,  # optional, enables Finnhub news path
    sentiment_client=None,  # NEW — crypto sentiment overlay
    repo=None,  # optional PortfolioRepository — enables trade-memory context
    strategy_name: str | None = None,
    regime: str | None = None,
) -> Signal:
    """Call LLM to review a quant signal. Returns original signal on any failure."""
    try:
        cache_key = (signal.symbol, signal.side)
        now = time.monotonic()
        if repo is not None:
            try:
                cached_row = repo.get_overlay_cache(signal.symbol, signal.side, _OVERLAY_TTL)
            except Exception:
                logger.warning("overlay cache read failed for %s, continuing without it", signal.symbol, exc_info=True)
                cached_row = None
            if cached_row is not None:
                logger.debug("overlay cache hit (db) symbol=%s side=%s", signal.symbol, signal.side)
                _log_llm_call(repo, "cache", signal.symbol, cache_hit=True, usage=None)
                return Signal(
                    symbol=signal.symbol,
                    side=cached_row["side"],
                    strength=cached_row["strength"],
                    reason=cached_row["reason"],
                )
        elif cache_key in _OVERLAY_CACHE:
            ts, cached = _OVERLAY_CACHE[cache_key]
            if now - ts < _OVERLAY_TTL:
                logger.debug("overlay cache hit symbol=%s side=%s age=%.0fs", signal.symbol, signal.side, now - ts)
                _log_llm_call(repo, "cache", signal.symbol, cache_hit=True, usage=None)
                return cached

        is_crypto = "/" in signal.symbol
        system_prompt = _CRYPTO_SYSTEM_PROMPT if is_crypto else _EQUITY_SYSTEM_PROMPT

        # Use Finnhub news if available, else Alpaca news
        from trader.overlay.news_context import fetch_news_with_fallback
        news = fetch_news_with_fallback(signal.symbol, config) if config else fetch_news(signal.symbol)
        news_section = news if news else "No recent news available."

        sentiment_str = ""
        if is_crypto and sentiment_client is not None:
            snap = sentiment_client.get_sentiment(signal.symbol)
            sentiment_str = sentiment_client.format_for_overlay(snap)

        user_message = (
            f"Signal: {signal.side} {signal.symbol} | "
            f"strength={signal.strength:.2f} | reason: {signal.reason}\n\n"
            f"{_bars_context(signal.symbol, bars)}\n\n"
            f"{news_section}"
        )
        if sentiment_str:
            user_message += f"\n\n{sentiment_str}"

        memory_shadow = bool(config and getattr(config.risk, "trade_memory_shadow", False))
        memory_live = bool(config and getattr(config.risk, "trade_memory_live", False))
        if repo is not None and (memory_shadow or memory_live):
            try:
                outcomes = repo.get_recent_outcomes(symbol=signal.symbol, limit=3)
                if outcomes:
                    lines = [f"Recent closed trades on {signal.symbol}:"]
                    for o in outcomes:
                        lines.append(
                            f"- {o['closed_at'][:10]} {o['strategy']}: {o['pnl_pct']:+.1%} "
                            f"({o['exit_reason']}). Entry rationale was: "
                            f"{o.get('entry_overlay_rationale') or 'n/a'}"
                        )
                    memory_section = "\n".join(lines)
                    if memory_live:
                        user_message += f"\n\n{memory_section}"
                    else:
                        logger.info("trade_memory shadow symbol=%s would inject: %s", signal.symbol, memory_section)
            except Exception:
                logger.warning("trade memory lookup failed for %s, continuing without it", signal.symbol)

        logger.info(
            "overlay request symbol=%s side=%s strength=%.2f news_lines=%d",
            signal.symbol, signal.side, signal.strength,
            news_section.count("\n") + 1 if news else 0,
        )
        logger.debug("overlay user_message:\n%s", user_message)

        raw, usage = call_llm(system_prompt, user_message, 256, groq_key, groq_model, claude_key, claude_model, gemini_key, gemini_model)
        if not raw:
            logger.warning("overlay: no LLM response for %s, passing through", signal.symbol)
            return signal
        _log_llm_call(repo, usage.provider if usage else "unknown", signal.symbol, cache_hit=False, usage=usage)

        parsed = _parse_response(raw)
        logger.info(
            "overlay response symbol=%s action=%s strength=%s rationale=%r",
            signal.symbol, parsed.get("action"), parsed.get("strength"), parsed.get("rationale", ""),
        )

        action = parsed.get("action")
        rationale = str(parsed.get("rationale", ""))

        if action not in {"approve", "veto"}:
            logger.warning("overlay: invalid action %r for %s, approving", action, signal.symbol)
            action = "approve"

        raw_strength = parsed.get("strength")
        try:
            strength = float(raw_strength)
            if not (0.0 <= strength <= 1.0):
                raise ValueError
        except (TypeError, ValueError):
            logger.warning("overlay: bad strength %r for %s, using original", raw_strength, signal.symbol)
            strength = signal.strength

        if action == "veto":
            result = Signal(
                symbol=signal.symbol,
                side="hold",
                strength=0.0,
                reason=f"[overlay veto] {rationale}",
            )
        else:
            result = Signal(
                symbol=signal.symbol,
                side=signal.side,
                strength=float(strength),
                reason=f"[overlay approved] {rationale}",
            )

        if repo is not None:
            try:
                repo.set_overlay_cache(signal.symbol, signal.side, result.side, result.strength, result.reason)
            except Exception:
                logger.warning("overlay cache write failed for %s", signal.symbol, exc_info=True)
        else:
            _OVERLAY_CACHE[cache_key] = (now, result)
        return result

    except Exception as exc:  # noqa: BLE001
        logger.warning("overlay failed for %s, passing through: %s", signal.symbol, exc)
        return signal
