"""LLM overlay — Phase 5.

Non-load-bearing: any failure returns the original signal unchanged.
LLM may veto (side→"hold", strength=0.0) or adjust strength ∈ [0.0, 1.0].
It never originates a trade, flips buy↔sell, or sets position size.
"""
from __future__ import annotations

import json
import logging
import re
import time

import pandas as pd

from trader.overlay.llm_client import call_llm
from trader.overlay.news_context import fetch_news
from trader.strategy.base import Signal

logger = logging.getLogger(__name__)

# ---- In-process overlay cache ----

# (symbol, side) -> (monotonic_timestamp, Signal)
_OVERLAY_CACHE: dict[tuple[str, str], tuple[float, Signal]] = {}
_OVERLAY_TTL = 300.0  # 5 minutes


def _clear_overlay_cache() -> None:
    """Test helper — clears the in-process overlay cache."""
    _OVERLAY_CACHE.clear()


# ---- System prompts ----

_EQUITY_SYSTEM_PROMPT = """\
You are a senior quantitative equity analyst at a systematic trading fund. You review
trade signals generated by moving-average crossover strategies on US equities.
Trades are swing positions (2-5 day holds). A hard risk gate enforces position limits
regardless of your output.

VETO the signal if ANY of the following apply:
- Earnings release scheduled within the next 2 trading days for this stock
- Major FDA, DOJ, SEC, or regulatory decision expected imminently
- Stock gapped more than 3% at today's open (momentum signal is stale/unreliable)
- Clearly adverse breaking news: executive departure, fraud allegation, major litigation,
  product recall, credit downgrade, or similar material negative event
- Broad market circuit-breaker conditions or Federal Reserve rate decision same day

REDUCE STRENGTH (approve with lower value) for:
- Elevated but non-decisive uncertainty (sector rotation, mild macro headwinds)
- Mixed news with no clear material catalyst

APPROVE with original strength when:
- News is neutral, positive, or irrelevant to the signal thesis
- No news available or you are uncertain — default bias is APPROVE, not veto

Before deciding, briefly weigh the strongest bull case (why this signal is valid now)
against the strongest bear case (why this signal might be wrong) given the news context.
Let that tension inform your strength value and whether to veto.

Reserve veto for clear, material, signal-invalidating events only. A false veto costs
edge; a missed veto costs at most one trade — the risk gate still protects.

NEVER flip buy to sell or sell to buy. NEVER originate a trade. NEVER increase
strength above what the strategy reported.

Respond ONLY with valid JSON — no markdown, no text outside the JSON object:
{"action": "approve"|"veto", "strength": <float 0.0-1.0>, "rationale": "<one sentence>"}
"""

_CRYPTO_SYSTEM_PROMPT = """\
You are a senior quantitative crypto analyst at a systematic trading fund. You review
trade signals generated by EMA crossover strategies on crypto assets (BTC/USD, ETH/USD,
and similar). The market runs 24/7 with no earnings events. A hard risk gate enforces
position limits regardless of your output.

VETO the signal if ANY of the following apply:
- Major exchange hack, insolvency, or trading halt announced (Binance, Coinbase, Kraken, etc.)
- Network-level exploit or critical smart contract vulnerability disclosed for this asset
- Concrete government ban or seizure order targeting this specific cryptocurrency
- Clearly adverse breaking news: founder fraud, protocol failure, major de-pegging event
- Broad market circuit-breaker conditions or Federal Reserve rate decision same day

REDUCE STRENGTH (approve with lower value) for:
- Elevated regulatory uncertainty without a concrete ban (proposed legislation, warnings)
- Mixed sentiment with no clear material catalyst
- Unusually high volatility without a directional catalyst

APPROVE with original strength when:
- News is neutral, positive, or irrelevant to the signal thesis
- No news available or you are uncertain — default bias is APPROVE, not veto

Before deciding, briefly weigh the strongest bull case (why this signal is valid now)
against the strongest bear case (why this signal might be wrong) given the news context.
Let that tension inform your strength value and whether to veto.

Reserve veto for clear, material, signal-invalidating events only. A false veto costs
edge; a missed veto costs at most one trade — the risk gate still protects.

NEVER flip buy to sell or sell to buy. NEVER originate a trade. NEVER increase
strength above what the strategy reported.

Respond ONLY with valid JSON — no markdown, no text outside the JSON object:
{"action": "approve"|"veto", "strength": <float 0.0-1.0>, "rationale": "<one sentence>"}
"""


def _bars_context(symbol: str, bars: pd.DataFrame) -> str:
    if bars.empty or len(bars) < 2:
        return f"Insufficient bar data for {symbol}."
    close = bars["close"]
    last_close = float(close.iloc[-1])
    lookback_20 = min(20, len(close) - 1)
    pct_20d = (close.iloc[-1] / close.iloc[-(lookback_20 + 1)] - 1) * 100
    lookback_10 = min(10, len(close) - 1)
    returns_10 = close.pct_change().dropna().iloc[-lookback_10:]
    vol_10d = float(returns_10.std() * (252 ** 0.5) * 100) if len(returns_10) > 1 else 0.0
    n_days = len(close)
    return (
        f"Market context ({symbol}, last {n_days} trading days):\n"
        f"- Last close: ${last_close:.2f}\n"
        f"- {lookback_20}-day price change: {pct_20d:+.1f}%\n"
        f"- {lookback_10}-day annualized volatility: {vol_10d:.1f}%"
    )


def _parse_response(text: str) -> dict:
    """Parse LLM response, stripping markdown fences if present."""
    text = text.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    return json.loads(text.strip())


def apply_claude_overlay(
    signal: Signal,
    bars: pd.DataFrame,
    groq_key: str | None,
    groq_model: str,
    claude_key: str | None,
    claude_model: str,
    gemini_key: str | None = None,
    gemini_model: str = "gemini-3.1-flash-lite",
    config=None,  # optional, enables Finnhub news path
    sentiment_client=None,  # NEW — crypto sentiment overlay
) -> Signal:
    """Call LLM to review a quant signal. Returns original signal on any failure."""
    try:
        cache_key = (signal.symbol, signal.side)
        now = time.monotonic()
        if cache_key in _OVERLAY_CACHE:
            ts, cached = _OVERLAY_CACHE[cache_key]
            if now - ts < _OVERLAY_TTL:
                logger.debug("overlay cache hit symbol=%s side=%s age=%.0fs", signal.symbol, signal.side, now - ts)
                return cached

        is_crypto = "/" in signal.symbol
        system_prompt = _CRYPTO_SYSTEM_PROMPT if is_crypto else _EQUITY_SYSTEM_PROMPT

        # Use Finnhub news if available, else Alpaca news
        from trader.overlay.news_context import fetch_news_with_fallback
        news = fetch_news_with_fallback(signal.symbol, config) if config else fetch_news(signal.symbol)
        news_section = news if news else "No recent news available."

        sentiment_str = ""
        is_crypto = "/" in signal.symbol
        if is_crypto and sentiment_client is not None:
            snap = sentiment_client.get_sentiment(signal.symbol)
            sentiment_str = sentiment_client.format_for_overlay(snap)

        user_message = (
            f"Signal: {signal.side} {signal.symbol} | "
            f"strength={signal.strength:.2f} | reason: {signal.reason}\n\n"
            f"{_bars_context(signal.symbol, bars)}\n\n"
            f"{news_section}"
        )
        if sentiment_str:
            user_message += f"\n\n{sentiment_str}"

        logger.info(
            "overlay request symbol=%s side=%s strength=%.2f news_lines=%d",
            signal.symbol, signal.side, signal.strength,
            news_section.count("\n") + 1 if news else 0,
        )
        logger.debug("overlay user_message:\n%s", user_message)

        raw = call_llm(system_prompt, user_message, 256, groq_key, groq_model, claude_key, claude_model, gemini_key, gemini_model)
        if not raw:
            logger.warning("overlay: no LLM response for %s, passing through", signal.symbol)
            return signal

        parsed = _parse_response(raw)
        logger.info(
            "overlay response symbol=%s action=%s strength=%s rationale=%r",
            signal.symbol, parsed.get("action"), parsed.get("strength"), parsed.get("rationale", ""),
        )

        action = parsed.get("action")
        strength = parsed.get("strength")
        rationale = str(parsed.get("rationale", ""))

        if action not in {"approve", "veto"}:
            raise ValueError(f"invalid action: {action!r}")
        if not isinstance(strength, (int, float)) or not (0.0 <= float(strength) <= 1.0):
            raise ValueError(f"strength out of range: {strength!r}")

        if action == "veto":
            result = Signal(
                symbol=signal.symbol,
                side="hold",
                strength=0.0,
                reason=f"[overlay veto] {rationale}",
            )
        else:
            result = Signal(
                symbol=signal.symbol,
                side=signal.side,
                strength=float(strength),
                reason=f"[overlay approved] {rationale}",
            )

        _OVERLAY_CACHE[cache_key] = (now, result)
        return result

    except Exception as exc:  # noqa: BLE001
        logger.warning("overlay failed for %s, passing through: %s", signal.symbol, exc)
        return signal
